{{- if .Values.agentManager.create }}
apiVersion: agentmanager.perfectscale.io/v1alpha1
kind: AgentManager
metadata:
  name: agentmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psc-agents-operator.labels" . | nindent 4 }}
spec:
  clustername: {{ required "agentManager.clusterName is required when agentManager.create is true" .Values.agentManager.clusterName | quote }}
  {{- with .Values.agentManager.clusterUid }}
  clusteruid: {{ . | quote }}
  {{- end }}
  credentials:
    name: {{ .Values.secret.secretName | quote }}
  exporter:
    installationMode: {{ .Values.agentManager.exporter.installationMode | quote }}
    upgrade:
      mode: {{ .Values.agentManager.exporter.upgrade.mode | quote }}
      {{- if eq .Values.agentManager.exporter.upgrade.mode "manual" }}
      version: {{ required "agentManager.exporter.upgrade.version is required for manual mode" .Values.agentManager.exporter.upgrade.version | quote }}
      {{- end }}
  promexporter:
    installationMode: {{ .Values.agentManager.promexporter.installationMode | quote }}
    upgrade:
      mode: {{ .Values.agentManager.promexporter.upgrade.mode | quote }}
      {{- if eq .Values.agentManager.promexporter.upgrade.mode "manual" }}
      version: {{ required "agentManager.promexporter.upgrade.version is required for manual mode" .Values.agentManager.promexporter.upgrade.version | quote }}
      {{- end }}
  autoscaler:
    installationMode: {{ .Values.agentManager.autoscaler.installationMode | quote }}
    upgrade:
      mode: {{ .Values.agentManager.autoscaler.upgrade.mode | quote }}
      {{- if eq .Values.agentManager.autoscaler.upgrade.mode "manual" }}
      version: {{ required "agentManager.autoscaler.upgrade.version is required for manual mode" .Values.agentManager.autoscaler.upgrade.version | quote }}
      {{- end }}
{{- end }}
