apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "psc-agents-operator.fullname" . }}-operator-config
  labels:
  {{- include "psc-agents-operator.labels" . | nindent 4 }}
data:
  operator-config.yaml: |
    charts:
      base_url: {{ .Values.operatorConfig.charts.baseUrl | quote }}
    server:
      metrics_bind_address: {{ .Values.operatorConfig.server.metricsBindAddress | quote }}
      health_probe_bind_address: {{ .Values.operatorConfig.server.healthProbeBindAddress | quote }}
      leader_elect: {{ .Values.operatorConfig.server.leaderElect }}
      secure_metrics: {{ .Values.operatorConfig.server.secureMetrics }}
      enable_http2: {{ .Values.operatorConfig.server.enableHttp2 }}
    webhook:
      cert_path: {{ .Values.operatorConfig.webhook.certPath | quote }}
      cert_name: {{ .Values.operatorConfig.webhook.certName | quote }}
      cert_key: {{ .Values.operatorConfig.webhook.certKey | quote }}
    credentials:
      secret_name: {{ .Values.secret.secretName | quote }}
      key_client_id: "clientId"
      key_client_secret: "clientSecret"
    cluster:
      name: {{ .Values.agentManager.clusterName | quote }}
      uid: {{ .Values.agentManager.clusterUid | quote }}
    api_client:
      settings_url: {{ .Values.operatorConfig.apiClient.settingsUrl | quote }}
      auth_url: {{ .Values.operatorConfig.apiClient.authUrl | quote }}
