{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "perfectscale-agent.fullname" . }}
  labels: {{- include "perfectscale-agent.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- toYaml .Values.additionalLabels | nindent 4 }}
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "perfectscale-agent.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "perfectscale-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
