{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: {{ template "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}

rules:
  - apiGroups: [ "" ]
    resources: [ "nodes/proxy", "namespaces" ]
    verbs: [ "get","list" ]
{{- end }}
