{{- $fullName := include "helm.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.priorityClass.enabled }}
      priorityClassName: {{ .Values.priorityClass.name }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: depends-on
          image: "public.ecr.aws/perfectscale-io/alpine:3.17"
          command: [ 'sh' ]
          args: [ '-c', 'curl --retry-all-errors --retry 30 --retry-delay 5 -s {{ include "helm.exporter.ksmAddress" . }}; sleep {{ .Values.settings.initSleep | default "1s" }}' ]
{{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SERVICE_ID
            value: "{{ .Values.settings.serviceId }}"
          - name: ENV
            value: "{{ .Values.settings.env }}"
          - name: LOG_LEVEL
            value: "{{ .Values.settings.logLevel }}"
          - name: HTTP_PORT
            value: "{{ .Values.settings.httpPort }}"
          - name: SCRAPE_FREQUENCY_TIME
            value: "{{ .Values.settings.scrapingInterval }}"
          - name: KUBE_API_TIMEOUT
            value: "{{ .Values.settings.kubeAPITimeoutSec }}"
          - name: DATA_RETENTION_TIME
            value: "{{ .Values.settings.dataRetentionTime | default "15m" }}"
          - name: KSM_ADDRESS
            value: "{{ include "helm.exporter.ksmAddress" . }}"
          - name: CADVISOR_NUM_WORKERS
            value: "{{ .Values.settings.cAdvisorNumWorkers }}"
          - name: PS_URL
            value: "{{ .Values.settings.psUrl }}"
          - name: UPLOAD_POLICY_URL
            value: "{{ .Values.settings.uploadPolicyUrl }}"
          - name: RAW_TIME_WINDOW_SIZE_MINUTES
            value: "{{ .Values.settings.rawTimeWindowSizeMinutes | default "10m" }}"
          - name: UPLOAD_POLICY_REFRESH_PCT
            value: "{{ .Values.settings.policyRefreshPct | default "0.5" }}"
          - name: CLUSTER_UID
            value: "{{ include "helm.exporter.clusterUID" . }}"
          - name: DEMO_ENV_ADDRESS
            value: "{{ .Values.settings.demoEnvAddress }}"
          - name: ENABLE_PPROF
            value: "{{ .Values.settings.enablePProf | default "false" }}"
          - name: "KUBERNETES_CLIENT_BURST"
            value: "{{ .Values.settings.k8sClientBurst }}"
          - name: "KUBERNETES_CLIENT_QPS"
            value: "{{ .Values.settings.k8sClientQPS }}"
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name | default $fullName }}
                key: "clientId"
                optional: false
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name | default $fullName }}
                key: "clientSecret"
                optional: false
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secretName }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
