{{- $fullName := include "perfectscale-agent.fullname" . -}}
{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default $fullName }}
  annotations:
    "perfectscale-agent.sh/resource-policy": keep
  labels:
    {{- include "perfectscale-agent.labels" . | nindent 4 }}
type: Opaque
data:
  clientId: {{ .Values.secret.clientId | b64enc | quote }}
  clientSecret: {{ .Values.secret.clientSecret | b64enc | quote }}
{{ end }}
