{{- $altNames := list ( printf "%s.%s" (include "psc-autoscaler.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" (include "psc-autoscaler.fullname" .) .Release.Namespace ) -}}
{{- $ca := genCA "psc-autoscaler-ca" 1825 -}}
{{- $cert := genSignedCert ( include "psc-autoscaler.fullname" . ) nil $altNames 1825 $ca -}}
---
{{- if not .Values.admission.certManager.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "psc-autoscaler.fullname" . }}-tls
  labels:
    {{- include "psc-autoscaler.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- toYaml .Values.additionalLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.admission.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}     
data:
{{- if .Values.admission.staticCerts.enabled }}
  tls.crt: {{ .Values.admission.staticCerts.tlsCert }}
  tls.key: {{ .Values.admission.staticCerts.tlsKey }}
{{- else }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "psc-autoscaler.fullname" . }}
  labels:
    {{- include "psc-autoscaler.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- toYaml .Values.additionalLabels | nindent 4 }}
    {{- end }} 
{{- $hasAnnotations := .Values.admission.annotations }}
{{- if or $hasAnnotations .Values.admission.certManager.enabled }}
  annotations:
    {{- with $hasAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.admission.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "psc-autoscaler.fullname" . }}-ca
    {{- end }}
{{- end }}
webhooks:
  - name: pods.perfectscale.io
    {{- if and (.Values.settings.excludedNamespaces) (ne (.Values.settings.excludedNamespaces | toString) "[]") }}
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: {{ (.Values.settings).excludedNamespaces }}
    {{- end }}
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: "Namespaced"
    clientConfig:
      {{- if not .Values.admission.certManager.enabled }}
        {{- if .Values.admission.externalCertSecret.enabled }}
      caBundle: {{ .Values.admission.externalCertSecret.caCert }}
        {{- else if .Values.admission.staticCerts.enabled }}
      caBundle: {{ .Values.admission.staticCerts.caCert }}
        {{- else }}
      caBundle: {{ $ca.Cert | b64enc }}
        {{- end }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "psc-autoscaler.fullname" . }}
        path: /v1
        port: {{ (.Values.service).port | default 443 }}
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: {{ (.Values.admission).timeout | default 15 }}
    failurePolicy: {{ (.Values.admission).failurePolicy | default "Ignore" }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "psc-autoscaler.fullname" . }}
  labels:
    {{- include "psc-autoscaler.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- toYaml .Values.additionalLabels | nindent 4 }}
    {{- end }} 
{{- $hasAnnotations := .Values.admission.annotations }}
{{- if or $hasAnnotations .Values.admission.certManager.enabled }}
  annotations:
    {{- with $hasAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.admission.certManager.enabled }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "psc-autoscaler.fullname" . }}-ca
    {{- end }}
{{- end }}
webhooks:
  - name: configs.perfectscale.io
    rules:
      - apiGroups: [ "perfectscale.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "clusterautomationconfigs" ]
        scope: "*"
      - apiGroups: [ "perfectscale.io" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE", "UPDATE" ]
        resources: [ "namespaceautomationconfigs", "workloadautomationconfigs" ]
        scope: "Namespaced"
    clientConfig:
      {{- if not .Values.admission.certManager.enabled }}
        {{- if .Values.admission.externalCertSecret.enabled }}
      caBundle: {{ .Values.admission.externalCertSecret.caCert }}
        {{- else if .Values.admission.staticCerts.enabled }}
      caBundle: {{ .Values.admission.staticCerts.caCert }}
        {{- else }}
      caBundle: {{ $ca.Cert | b64enc }}
        {{- end }}
      {{- end }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "psc-autoscaler.fullname" . }}
        path: /v1/validate/config
        port: {{ (.Values.service).port | default 443 }}
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    timeoutSeconds: {{ (.Values.admission).timeout | default 15 }}
    failurePolicy: "Fail"
