{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "psc-autoscaler.fullname" . }}
rules:
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations" ]
    verbs: [ "create", "get", "delete", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list","watch","create", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "deployments", "statefulsets", "daemonsets", "jobs", "cronjobs" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "rollouts" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "perfectscale.io" ]
    resources: [ "workloads" ]
    verbs: [ "create", "get", "delete", "list", "patch", "update", "watch" ]
{{ end }}
