{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "psc-autoscaler.fullname" . }}
  labels: {{- include "psc-autoscaler.labels" . | nindent 4 }}
    {{- if .Values.additionalLabels }}
    {{- toYaml .Values.additionalLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "mutatingwebhookconfigurations", "validatingwebhookconfigurations" ]
    verbs: [ "create", "get", "delete", "list", "patch", "update", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "delete", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/resize" ]
    verbs: [ "patch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list","watch","create", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "replicasets", "deployments", "statefulsets", "daemonsets" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs", "cronjobs" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "argoproj.io" ]
    resources: [ "rollouts" ]
    verbs: [ "get", "list", "watch", "patch" ]
  - apiGroups: [ "perfectscale.io" ]
    resources: [ "workloads", "clusterautomationconfigs", "namespaceautomationconfigs", "workloadautomationconfigs", "workloadautomationstatuses" ]
    verbs: [ "create", "get", "delete", "list", "patch", "update", "watch" ]
{{ end }}
