apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: workloads.perfectscale.io
spec:
  # either Namespaced or Cluster
  scope: Namespaced
  # group name to use for REST API: /apis/<group>/<version>
  group: perfectscale.io
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: workloads
    # singular name to be used as an alias on the CLI and for display
    singular: workload
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Workload
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - workload
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                targetRef:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                namespace:
                  type: string
                revision: # Deprecated, use currentRevisionInfo or targetRevisionInfo.
                  type: string
                revisionHash:
                  type: string
                currentRevisionInfo:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    revision:
                      type: string
                    revisionHash:
                      type: string
                targetRevisionInfo:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    revision:
                      type: string
                    revisionHash:
                      type: string
                waste:
                  type: number
                  format: double
                updatedAt:
                  type: string
                appliedAt:
                  type: string
                indicators:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  additionalProperties:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    properties:
                      name:
                        type: string
                      type:
                        type: string
                      severity:
                        type: integer
                containers:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  additionalProperties:
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    properties:
                      name:
                        type: string
                      indicators:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        additionalProperties:
                          type: object
                          x-kubernetes-preserve-unknown-fields: true
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            severity:
                              type: integer
                      current:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        properties:
                          requests:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                      currentSpec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        properties:
                          requests:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                      target:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        properties:
                          requests:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                      targetSpec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        properties:
                          requests:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          limits:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
