createNamespace: false
controllerManager:
  manager:
    args:
      - --config=/etc/operator/operator-config.yaml
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image:
      repository: public.ecr.aws/perfectscale-io/psc-agents-operator
      tag: ""
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 3
  tolerations: []
  topologySpreadConstraints: []
metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
serviceAccount:
  annotations: {}
  automount: true
  create: true
  name: ""
operatorConfig:
  charts:
    baseUrl: "https://perfectscale-io.github.io"
  server:
    metricsBindAddress: ":8443"
    healthProbeBindAddress: ":8081"
    leaderElect: true
    secureMetrics: true
    enableHttp2: false
  webhook:
    certPath: ""
    certName: "tls.crt"
    certKey: "tls.key"
  apiClient:
    settingsUrl: "https://api.app.perfectscale.io/psc-settings"
    authUrl: "https://api.app.perfectscale.io/psc-tenant-manager"
secret:
  create: false
  secretName: "psc-credentials"
  clientId: ""
  clientSecret: ""
agentManager:
  create: false
  clusterName: ""
  clusterUid: ""
  exporter:
    installationMode: "off"
    upgrade:
      mode: "auto"
      version: ""
  promexporter:
    installationMode: "off"
    upgrade:
      mode: "auto"
      version: ""
  autoscaler:
    installationMode: "off"
    upgrade:
      mode: "auto"
      version: ""
image:
  tag: v0.2.0
