apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "psc-agent-operator.fullname" . }}-config
  labels:
  {{- include "psc-agent-operator.labels" . | nindent 4 }}
data:
  operator-config.yaml: |
    charts:
      base_url: {{ .Values.operatorConfig.charts.baseUrl | quote }}
    server:
      metrics_bind_address: {{ .Values.operatorConfig.server.metricsBindAddress | quote }}
      health_probe_bind_address: {{ .Values.operatorConfig.server.healthProbeBindAddress | quote }}
      leader_elect: {{ .Values.operatorConfig.server.leaderElect }}
      secure_metrics: {{ .Values.operatorConfig.server.secureMetrics }}
      enable_http2: {{ .Values.operatorConfig.server.enableHttp2 }}
    webhook:
      cert_path: "/tmp/k8s-webhook-server/serving-certs"
      cert_name: "tls.crt"
      cert_key: "tls.key"
      singleton_name: {{ .Values.webhook.singletonName | default "agents" | quote }}
    credentials:
      secret_name: {{ .Values.secret.secretName | quote }}
      key_client_id: "clientId"
      key_client_secret: "clientSecret"
    cluster:
      name: {{ .Values.agents.clusterName | quote }}
      uid: {{ .Values.agents.clusterUID | quote }}
    api_client:
      settings_url: {{ .Values.operatorConfig.apiClient.settingsUrl | quote }}
      auth_url: {{ .Values.operatorConfig.apiClient.authUrl | quote }}
      telemetry_url: {{ .Values.operatorConfig.apiClient.telemetryUrl | quote }}
