apiVersion: v1
kind: Service
metadata:
  name: {{ include "psc-agent-operator.fullname" . }}-webhook
  labels:
  {{- include "psc-agent-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP
  selector:
    app.kubernetes.io/component: operator
  {{- include "psc-agent-operator.selectorLabels" . | nindent 4 }}
