apiVersion: perfectscale.io/v1
kind: ClusterAutomationConfig
metadata:
  name: cluster-automation-config
spec:
  automation:
    operational:
      stopAllAutomation: false
      automationStrategy: "inPlace" # "inPlace" or "evictMutate", default is "inPlace"
      podResizePendingStrategy: "rollingRestart" # "rollingRestart" or "deleteRecreatePendingPod", default is "rollingRestart"
    workloadTypes:
      #  You should consider if you want to enable StatefulSets automation.
      #  You might want a human eye while restarting production databases, in general, pods with persistent volume are more fragile.
      #  As well, if your StatefulSet runs on dedicated nodes, reducing workload resources will not help to reduce the cost
      StatefulSet:
        operational:
          automationStrategy: "inPlace" # "inPlace" or "evictMutate", default is "inPlace"
          podResizePendingStrategy: "rollingRestart" # "rollingRestart" or "deleteRecreatePendingPod", default is "rollingRestart"
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      Deployment:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      DaemonSet:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      CronJob:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      Job:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
