apiVersion: perfectscale.io/v1
kind: ClusterAutomationConfig
metadata:
  name: cluster-automation-config
spec:
  automation:
    operational:
      stopAllAutomation: false
    workloadTypes:
      Deployment:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      DaemonSet:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      CronJob:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
      Job:
        operational:
          automationMode: "Enabled"
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                keepLimit: true
            memoryManagement:
              request:
                increaseEnabled: false
                decreaseEnabled: true
              limit:
                increaseEnabled: false
                decreaseEnabled: false
