apiVersion: perfectscale.io/v1
kind: ClusterNodeGroupAutomationConfig
metadata:
  name: cluster-nodegroup-automation
spec:
  automation:
    operational:
      stopAllAutomation: false
      cleanUpAutomation: false
    karpenter:
      operational:
        automationMode: Enabled
        stopAllAutomation: false
        cleanUpAutomation: false
    binpacking:
      operational:
        automationMode: DryRun
        evictBarePods: true
