{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "psc-prom-exporter.fullname" . }}
  labels:
    {{- include "psc-prom-exporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - nonResourceURLs:
      - "/version"
    verbs:
      - "get"
{{- end }}
