{{- if .Values.alerts.datadogMonitor.enabled }}
{{- range .Values.alerts.datadogMonitor.rules }}
{{- if .enabled }}
---
apiVersion: datadoghq.com/v1alpha1
kind: DatadogMonitor
metadata:
  name: {{ include "helm.fullname" $ }}-{{ kebabcase .alert }}
  {{- if $.Values.alerts.datadogMonitor.namespace }}
  namespace: {{ $.Values.alerts.datadogMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
    {{- with $.Values.alerts.datadogMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  query: {{ .query | quote }}
  type: {{ .type | quote }}
  name: {{ .alert | quote }}
  message: {{ .message | quote }}
  {{- if .runbook }}
  options:
    escalation_message: {{ .runbook | quote }}
  {{- end }}
  {{- with .tags }}
  tags:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
