{{- $fullName := include "psc-prom-exporter.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "psc-prom-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psc-prom-exporter.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "psc-prom-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "psc-prom-exporter.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.scrapers.prometheus.enabled }}
        {{- with .Values.scrapers.prometheus.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- if and .Values.scrapers.datadog.enabled (eq .Values.scrapers.datadog.adVersion "v1") }}
        {{- include "datadogAD.v1annotations" .Values.scrapers.datadog | nindent 8 }}
        {{- end }}
        {{- if and .Values.scrapers.datadog.enabled (eq .Values.scrapers.datadog.adVersion "v2") }}
        {{- include "datadogAD.v2annotations" .Values.scrapers.datadog | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if ne .Values.priorityClass.enabled false}}
      priorityClassName: {{ .Values.priorityClass.name | default "perfectscale-exporter" }}
      {{- end }}
      serviceAccountName: {{ include "psc-prom-exporter.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "./app"
            - "serve"
          volumeMounts:
            - name: config
              mountPath: /opt/exporter-config.yaml
              subPath: config.yaml
            - name: temp-storage
              mountPath: /opt/temp
          env:
{{- if eq .Values.settings.env "dev" }}
          - name: GOMEMLIMIT
            value: "{{ .Values.resources.requests.memory }}B"
{{- end }}
          - name: SERVICE_ID
            value: "{{ .Values.settings.serviceId }}"
          - name: ENV
            value: "{{ .Values.settings.env }}"
          - name: LOG_LEVEL
            value: "{{ .Values.settings.logLevel }}"
          - name: HTTP_PORT
            value: "{{ .Values.settings.httpPort }}"
          - name: PUSH_TELEMETRY_FREQUENCY
            value: "{{ .Values.settings.pushTelemetryFrequency }}"
          - name: KUBE_API_TIMEOUT
            value: "{{ .Values.settings.kubeAPITimeoutSec }}"
          - name: PS_URL
            value: "{{ .Values.settings.psUrl }}"
          - name: UPLOAD_POLICY_URL
            value: "{{ .Values.settings.uploadPolicyUrl }}"
          - name: TELEMETRY_URL
            value: "{{ .Values.settings.telemetryUrl }}"
          - name: RAW_TIME_WINDOW_SIZE_MINUTES
            value: "{{ .Values.settings.rawTimeWindowSizeMinutes | default "10m" }}"
          - name: UPLOAD_POLICY_REFRESH_PCT
            value: "{{ .Values.settings.policyRefreshPct | default "0.5" }}"
          - name: CLUSTER_UID
            value: "{{ include "psc-prom-exporter.exporter.clusterUID" . }}"
          - name: CLUSTER_RESILIENCE_LEVEL
            value: "{{ .Values.settings.clusterResilienceLevel }}"
          - name: "KUBERNETES_CLIENT_BURST"
            value: "{{ .Values.settings.k8sClientBurst }}"
          - name: "KUBERNETES_CLIENT_QPS"
            value: "{{ .Values.settings.k8sClientQPS }}"
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name | default $fullName }}
                key: "clientId"
                optional: false
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name | default $fullName }}
                key: "clientSecret"
                optional: false
          - name: REMOTE_LOG_BATCH_SIZE
            value: "{{ include "psc-prom-exporter.exporter.remoteLogBatchSize" . }}"
          - name: REMOTE_LOG_BATCH_INTERVAL
            value: "{{ include "psc-prom-exporter.exporter.remoteLogBatchInterval" . }}"
          {{- if .Values.settings.httpProxyEnabled | default false }}
          - name: HTTP_PROXY
            value: "{{ .Values.settings.httpProxy }}"
          - name: HTTPS_PROXY
            value: "{{ .Values.settings.httpsProxy }}"
          - name: NO_PROXY
            value: "{{ .Values.settings.noProxy }}{{ .Release.Name }}-kube-state-metrics"
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- if .Values.containerSecurityContext }}
          securityContext:
{{ toYaml .Values.containerSecurityContext | indent 12 }}
{{- end }}
      volumes:
        - name: config
          configMap:
            name: {{  include "psc-prom-exporter.fullname" .  }}
        - name: temp-storage
          emptyDir: {}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.secretName }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
