{{- if .Values.scrapers.serviceMonitor -}}
{{- if .Values.scrapers.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.scrapers.serviceMonitor.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  endpoints:
    - port: http
{{- if .Values.scrapers.serviceMonitor.interval }}
      interval: {{ .Values.scrapers.serviceMonitor.interval }}
{{- end }}
{{- if .Values.scrapers.serviceMonitor.path }}
      path: {{ .Values.scrapers.serviceMonitor.path }}
{{- end }}
{{- if .Values.scrapers.serviceMonitor.timeout }}
      scrapeTimeout: {{ .Values.scrapers.serviceMonitor.timeout }}
{{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
{{- end }}
{{- end }}
